
- name: NFS client installation and nfs server mount
  vars:
    ansible_python_interpreter: "/usr/bin/python3" # set ansible interpreter to python3
  vars_files:
    - ansible_vars.yaml # ansible variables to install nfs client
  hosts: "{{ hosts }}"
  become: true
  gather_facts: no
  user: "{{ user }}" # pass this as a parameter

  tasks:
    - name: Install nfs on the client instance (Ubuntu or Debian)
      command: apt-get install nfs-common 
      when: (os_flavour == "Ubuntu" or os_flavour == "Debian" or os_flavour == "ubuntu" or os_flavour == "debian")

    - name: Install nfs on the client instance (CentOS)
      command: yum install nfs-utils nfs-utils-lib
      when: (os_flavour == "CentOS" or os_flavour == "centOS")

    - name: Create an nfs directory where to mount nfs server dir
      file:
        path: "{{ mount_dest_path }}"
        state: directory
        mode: "u=r,g=r,o=rwx" # might need to change these privileges
        recurse: yes

    - name: Mount nfs server directory to client location
      mount:
        path: "{{ mount_dest_path }}"
        src: "{{ nfs_server_ip }}:/nfs"
        fstype: nfs
        state: mounted